### Create Report

POST http://localhost:3000/reports
Content-Type: application/json

{
    "make" : "bmw",
    "model" : "sports",
    "year" : 2023,
    "mileage" : 1000,
    "lng" : 0,
    "lat" : 0,
    "price" : 60000
}

### Approve request
PATCH http://localhost:3000/reports/8
Content-Type: application/json

{
    "approved" : true
}

